// Objective-C API for talking to github.com/ichibankunio/podiumpuzzle/mobile Go package.
//   gobind -lang=objc github.com/ichibankunio/podiumpuzzle/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol MobileGameManager;
@class MobileGameManager;

@protocol MobileGameManager <NSObject>
/**
 * GetRecord(string)
 */
- (long)setLocation;
/**
 * IsJustTouch() bool
GetDataArray(data []int)
 */
- (NSString* _Nonnull)setRecord;
@end

FOUNDATION_EXPORT const int64_t MobileBUTTON_APP;
FOUNDATION_EXPORT const int64_t MobileBUTTTON_TWEET;
FOUNDATION_EXPORT const int64_t MobileSCREEN_HEIGHT;
FOUNDATION_EXPORT const int64_t MobileSCREEN_WIDTH;

/**
 * Dummy is a dummy exported function.

gomobile doesn't compile a package that doesn't include any exported function.
Dummy forces gomobile to compile this package.
 */
FOUNDATION_EXPORT void MobileDummy(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetButtonData(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetHighScore(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetResultText(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT long MobileGetScreenHeight(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT long MobileGetScreenWidth(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT long MobileGetState(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT void MobileSetHighScore(id<MobileGameManager> _Nullable gm);

FOUNDATION_EXPORT void MobileSetLang(id<MobileGameManager> _Nullable gm);

@class MobileGameManager;

@interface MobileGameManager : NSObject <goSeqRefInterface, MobileGameManager> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * GetRecord(string)
 */
- (long)setLocation;
/**
 * IsJustTouch() bool
GetDataArray(data []int)
 */
- (NSString* _Nonnull)setRecord;
@end

#endif
